### ISSUE TITLE
README code examples could do with some syntax cleanup

### ISSUE THREAD

**Issue by orta** [smyrgl/RESTEasy#5]
![screen shot 2014-04-30 at 12 10 53](https://cloud.githubusercontent.com/assets/49038/2839452/61c4b482-d047-11e3-8dcf-0f7f3813e586.png)

Can't really glance over these ^

**Comment by smyrgl** [comment]
I assume you mean the formatting not syntax?  I switched to box literals to cut down on the verbiage and made the dictionary declarations separate.  Hopefully that makes it a bit more readable, although what I really need is a TGResourceRESTActionsAll option.

**Comment by smyrgl** [comment]
By the way the API documentation might be more useful than the README...unfortunately Cocoadocs is having some problems with parsing of new pod docsets which I sent them an email about.  However the docs generate just fine so if you want to take a look just download the project and run rake docs:generate.
